### ISSUE TITLE
problem source "http://geolocation.googlecode.com/svn/wiki/pdf/ukfsst-ref.pdf"

### ISSUE THREAD

**Issue by ghost** [positioning/kalmanfilter#10]
Hi Tim,

I've a problem when a try to access to this document "ukfsst-ref.pdf"
I have :  "404. That’s an error.
The requested URL /svn/wiki/pdf/ukfsst-ref.pdf was not found on this server"

how can I solve it?

Thanks in advance 

Cheers,

Pierre

**Comment by tagtuna** [comment]
Sorry about that. This should do for now. Will update the link soon

https://github.com/positioning/kalmanfilter/tree/master/ukfsst/inst/doc
