### ISSUE TITLE
Problem with get.sst.from.server

### ISSUE THREAD

**Issue by Anofia** [positioning/kalmanfilter#6]
Hi, 

I have a problem when running the get.sst.from.server function. When I run the script I get this error

"Contacting server for SST images within this date range: 2Dec2012 - 17Mar2013

trying URL 'http://www.esrl.noaa.gov/psd/cgi-bin/GrADS.pl?dataset=NOAA+Optimum+Interpolation+%28OI%29+SST+V2&DB_did=62&file=%2FDatasets%2Fnoaa.oisst.v2%2Fsst.wkmean.1990-present.nc&variable=sst&DB_vid=1296&DB_tid=54256&units=degC&longstat=Mean&DB_statistic=Mean&stat=&lat-begin=50.5S&lat-end=67.5N&lon-begin=202.5E&lon-end=231.5E&dim0=time&year_begin=2012&mon_begin=Dec&day_begin=2&year_end=2013&mon_end=Mar&day_end=17&X=lon&Y=lat&output=file&bckgrnd=black&use_color=on&cint=&range1=&range2=&scale=100&submit=Create+Plot+or+Subset+of+Data'
Content type 'text/html; charset=ISO-8859-1' length 200 bytes
opened URL
downloaded 10 Kb

Error in strsplit(unlist(strsplit(dstring, "a href="))[2], ">") : 
  non-character argument
In addition: Warning messages:
1: In download.file(link, fname, mode = "wb") :
  downloaded length 15137 != reported length 200
2: In download.file(opt, fname, mode = "wb") :
  downloaded length 10341 != reported length 200
Called from: top level "

I went through the function steps and, if i understood the code correctly, I believe the problem is when getting the ftp to download the data (dstring <- dfile[grep("ftp://ftp.cdc.noaa.gov/", dfile)]),  even in the site after creating the map with the subset the link does not appear.
I really need these data, is there an alternative to get the sst files?

Thank you very much

**Comment by tagtuna** [comment]
Thanks for bringing this issue up. It's strange, I suspect something has changed at the NOAA site. I will look into it, and see what I can do. If you need anything urgent, email me directly at tim.lam@umb.edu

**Comment by tagtuna** [comment]
Hi Anofia - I believe the NOAA ESRL subset API is being upgraded/ temporarily unavailable. The script basically recreates the web form processes, as if you were to request data manually. I tried in person to do it through the web form, but was experienced same issues. Feel free to file an issue with ESRL, as I am going to do so. My recommendation is to stay put for a few days (usually the problem goes away - been there before). Sorry about an external problem, beyond my control.

**Comment by Anofia** [comment]
Thank you very much for your answer, I will follow your advice and wait a few days.
